id = "unit-language"
name = "Unit Language"
version = "0.0.1"
schema_version = 1
authors = ["Nikhil Idiculla"]
description = "Language support for Unit (.unit files)"

[grammars.unit]
repository = "https://github.com/tsnl/tree-sitter-unit"
rev = "main"
